version: 2.1

setup: true

jobs:
  check_for_changes:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Check for changes in "my_package" directory
          command: |
            echo "Checking for changes in 'my_package' directory..."
            git fetch origin
            if git diff --quiet origin/main...HEAD -- my_package/; then
              echo "No changes detected in my_package"
              echo 'export SKIP_PIPELINE="true"' >> $BASH_ENV
            else
              echo "Changes detected in my_package"
              echo 'export SKIP_PIPELINE="false"' >> $BASH_ENV
            fi
      - run:
          name: Trigger my_package Build
          command: |
            if [ "$SKIP_PIPELINE" = "false" ]; then
              circleci config process .circleci/ocpipes.yml > processed.yml
              circleci local execute -c processed.yml || exit 1
            else
              echo "Skipping my_package build"
            fi

workflows:
  version: 2
  check-changes:
    jobs:
      - check_for_changes