version: 2.1

jobs:
  check_for_changes:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Check for changes in "my_package" directory
          command: |
            echo "Checking for changes in 'my_package' directory..."
            git fetch origin
            if git diff --quiet origin/main...HEAD -- my_package/; then
              echo "No changes detected in my_package"
              echo 'export SKIP_PIPELINE="true"' >> $BASH_ENV
            else
              echo "Changes detected in my_package"
              echo 'export SKIP_PIPELINE="false"' >> $BASH_ENV
            fi
      - run:
          name: Trigger my_package Build
          command: |
            if [ "$SKIP_PIPELINE" = "false" ]; then
              echo "Triggering my_package build..."
              curl -X POST --header "Content-Type: application/json" --header "Circle-Token: $CIRCLE_TOKEN" -d '{
              "parameters": {
                "myparam": "./myspecialdir",
                "myspecialversion": "4.8.2"
              }
            }' https://circleci.com/api/v2/project/github/surendra136938/conda-package-example/pipeline

            else
              echo "Skipping my_package build"
            fi

workflows:
  version: 2
  check-changes:
    jobs:
      - check_for_changes

# curl -u ${CIRCLECI_TOKEN}: \
#                 -d '{
#                       "branch": "circleci-project-setup",
#                       "parameters": {
#                         "CIRCLE_JOB": "build_and_upload"
#                       }
#                     }' \
#                 -H "Content-Type: application/json" \
#                 -X POST https://circleci.com/api/v2/project/github/surendra136938/conda-package-example/pipeline