version: 2.1

setup: true

jobs:
  check_for_changes:
    docker:
      - image: circleci/python:3.8  # Or any image of your choice
    steps:
      - checkout
      - run:
          name: Check for changes in "my_package" directory
          command: |
            if git diff --quiet origin/main...HEAD -- my_package/; then
              echo "No changes detected in my_package"
              circleci-agent step halt
            else
              echo "Changes detected in my_package"
   # No need to use a variable for skipping, halt directly stops execution.

      - run:
          name: Trigger Main Pipeline
          command: |
            circleci config process .circleci/config.yml > processed.yml
            circleci local execute -c processed.yml

workflows:
  version: 2
  check-changes:
    jobs:
      - check_for_changes
